[package]
name = "ru"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.180"
native-tls = "0.2.14"
rustls = "0.23.36"
rustls-native-certs = "0.8.3"
url = "2.5.8"

[build-dependencies]
pkg-config = "0.3.32"
